#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomControls.Resource", IsApplication=true)]

namespace CustomControls
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int awv_centerTextColor = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int awv_dividerTextColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int awv_initialPosition = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int awv_isLoop = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int awv_itemsVisibleCount = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int awv_lineSpace = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int awv_outerTextColor = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int awv_scaleX = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int awv_textsize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle_textview = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int seek_thumb = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int seekbar_horizontal = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int loopView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int loopView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int loopView2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int loopView3 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int test = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Widget_SeekBar_Normal = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] androidWheelView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 2
			public const int androidWheelView_awv_centerTextColor = 2;
			
			// aapt resource value: 4
			public const int androidWheelView_awv_dividerTextColor = 4;
			
			// aapt resource value: 7
			public const int androidWheelView_awv_initialPosition = 7;
			
			// aapt resource value: 6
			public const int androidWheelView_awv_isLoop = 6;
			
			// aapt resource value: 5
			public const int androidWheelView_awv_itemsVisibleCount = 5;
			
			// aapt resource value: 1
			public const int androidWheelView_awv_lineSpace = 1;
			
			// aapt resource value: 3
			public const int androidWheelView_awv_outerTextColor = 3;
			
			// aapt resource value: 8
			public const int androidWheelView_awv_scaleX = 8;
			
			// aapt resource value: 0
			public const int androidWheelView_awv_textsize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
